In [2]:
import numpy as np

In [8]:
#Arreglos
x=np.array([1,2,3,4])
print(x[3])
print(x[1:3])


4
[2 3]


In [9]:
y=np.zeros(5)
y

array([0., 0., 0., 0., 0.])

In [10]:
z=np.ones((4,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
print(type(y))
print(type(z[1][1]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [16]:
r=np.linspace(1,10,10)
r

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
g=np.array([['a','b','c'],['d','f','g']])
print(g)
print(type(g))
print(g.ndim)

[['a' 'b' 'c']
 ['d' 'f' 'g']]
<class 'numpy.ndarray'>
2


In [26]:
luke=[12,4,10,2]
np.sort(luke)

array([ 2,  4, 10, 12])

In [30]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('juan',10),('maria',70),('javier',33),('Samuel',15)]
usuarios = np.array(datos, dtype=cabeceras)

np.sort(usuarios, order='edad')

array([(b'juan', 10), (b'Samuel', 15), (b'javier', 33), (b'maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [31]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [38]:
np.full((2,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [39]:
np.diag([0,3,9,10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])